# 3. Find Anime TV series and their available streaming services
# Datasources: https://data.betweenourworlds.org/2018-06 https://dbpedia.org/sparql
SELECT ?animeName ?providerName WHERE {
  ?stream a bow:Stream.
  ?stream bow:object ?anime.
  ?stream bow:providedBy ?provider.

  ?anime a schema:TVSeries .
  ?anime schema:name ?animeName .

  ?provider foaf:name ?providerName

  FILTER (lang(?animeName) = 'en')
}
LIMIT 10
