# 5. Books by San Franciscans in Harvard Library
# Datasources: https://fragments.dbpedia.org/*/en https://data.linkeddatafragments.org/viaf https://data.linkeddatafragments.org/harvard
SELECT ?person ?name ?book ?title {
  ?person dbpedia-owl:birthPlace [ rdfs:label "San Francisco"@en ].
  ?viafID schema:sameAs ?person;
               schema:name ?name.
  ?book dc:contributor [ foaf:name ?name ];
              dc:title ?title.
}
