# Spouses and children of Bruce Willis
# Datasource: https://fragments.dbpedia.org/*/en
SELECT ?person
WHERE {
  [ rdfs:label "Bruce Willis"@en ]
    (dbpedia-owl:spouse|dbpedia-owl:child) ?person.
}
