# Places that have something to do with Barack Obama
# Datasource: https://fragments.dbpedia.org/*/en
SELECT ?place ?relation
WHERE {
  ?place rdf:type dbpedia-owl:Settlement;
         ?relation dbpedia:Barack_Obama;
}
